steps:
# ....
- name: gcr.io/cloud-builders/gcloud
  args:
  - kms
  - decrypt
  - --ciphertext-file=/infra_persistent_volume/infra/helm-deployment/app/templates/secret.yaml.enc
  - --plaintext-file=/infra_persistent_volume/infra/helm-deployment/app/templates/secret.yaml
  - --location=global
  - --keyring=helm-secrets
  - --key=app
  volumes:
  - name: 'infravol'
    path: '/infra_persistent_volume'

- name: ubuntu
  args: ['rm', '/infra_persistent_volume/infra/helm-deployment/app/templates/secret.yaml.enc']
  volumes:
  - name: 'infravol'
    path: '/infra_persistent_volume'
 
- name: 'gcr.io/$PROJECT_ID/helm'
  args: ['upgrade','app','/infra_persistent_volume/infra/helm-deployment/app/']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-b'
  - 'CLOUDSDK_CONTAINER_CLUSTER=gke-cluster'
  volumes:
  - name: 'infravol'
    path: '/infra_persistent_volume'

- name: ubuntu
  args: ['rm', '/infra_persistent_volume/infra/helm-deployment/app/templates/secret.yaml']
  volumes:
  - name: 'infravol'
    path: '/infra_persistent_volume'
